### ISSUE TITLE
Section 3.3 Tsunami Data

### ISSUE THREAD

**Issue by wantpinow** [nicholasjhorton/IS4inR#1]
So for IS4 the example in 3.3 uses the last 25 years of tsunami data (the book is a little old so that translates to the years 1987-2011). The book states (page 51) that there were 207 earthquakes from 1987-2011, however when you run:

`library(mosaic); library(readr)
options(digits=3)
Tsunami <- read_delim("http://www.amherst.edu/~nhorton/sdm4/data/Tsunami_Earthquakes.txt", 
  delim="\t")
dim(filter(Tsunami, Year >= 1987, Year <= 2011))`

you see that there are 219 earthquakes using the data we currently have. Also on page 52 of IS4 the minimum reported Magnitude is 3.7, however from looking at the text file containing the tsunami data (which Paul emailed Nick on Jan 16th), this datapoint does not exist, suggesting again that the data we have is different to that in the book. If anyone has an idea of why this is happening or access to earlier versions of the tsunami data, that would be very helpful.

**Comment by nicholasjhorton** [comment]
Close may be good enough here as well.
