### ISSUE TITLE
update formatting/examples/spacing/vcd::mosaic() per SDM4 

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/IS4inR#16]

**Comment by nicholasjhorton** [comment]
I've pushed updated pdf files for all of the chapters.  Can you please do a quick spin through these and let me know if you see any issues?  

Also there are some issues in Chapter23.Rmd: Error: Aesthetics must be either length 1 or the same as the data (2): colour

and Chapter20: Quitting from lines 111-119 (Chapter20.Rmd) 
Error: Aesthetics must be either length 1 or the same as the data (2): colour
In addition: Warning message:
Removed 1 rows containing non-finite values (stat_boxplot).

**Comment by sarahmcdonald20** [comment]
For chapter 20, do you mean we are removing those lines of code entirely? Or should I attempt to change it?

Went through all the pdfs, some minor spacing corrections in chapters 15, 18, and 20, but other than that the pdfs look good!

**Comment by nicholasjhorton** [comment]
Are you able to get this to compile using the ggformula version running with ggplot 2.3?

**Comment by nicholasjhorton** [comment]
@sarahmcdonald20 can you please let me know where things stand?  I see that Chapter02.Rmd has ye to be updated.

**Comment by nicholasjhorton** [comment]
Can you please update this  issue when you have a chance?

**Comment by sarahmcdonald20** [comment]
ready to republish

**Comment by nicholasjhorton** [comment]
Done, thanks!
