### ISSUE TITLE
Section 4.1 Apparent Difference in Wind Data

### ISSUE THREAD

**Issue by wantpinow** [nicholasjhorton/IS4inR#2]
Both IS4 and SDM4 give the example of 2011 wind speeds in 2011. From figure 4.1, we see that the 5-number summaries are the same in both books, suggesting the data is the same. However, figure 4.2 is clearly different between books when doing the same thing with the same data? Was this a mistake made in IS4 that was replicated in SDM4? I am unable to recreate the histograms of 4.2 from IS4.

**Comment by nicholasjhorton** [comment]
Let's just have you note that there are discrepancies from what's on that page (and leave it at that).
