### ISSUE TITLE
Section 4.5 Salaries for Different Years

### ISSUE THREAD

**Issue by wantpinow** [nicholasjhorton/IS4inR#3]
For figures 4.7 and 4.8 in IS4, the data of CEO's salaries in 2010 are used. SDM4 uses the data from 2012. Is the data from 2010 available? If anybody knows where it is located that would be of much use.

**Comment by nicholasjhorton** [comment]
Can we leave out this example and use another example from later in the chapter (for which data are available?)

**Comment by deveaux69** [comment]
Who are you asking?

I just spend 10 minutes searching my computer. I’m not sure I can find this particular set.

**Comment by nicholasjhorton** [comment]
These are all assigned to Patrick Frenett (so not to worry on your end).

nick

> On Jun 8, 2016, at 4:10 PM, deveaux69 notifications@github.com wrote:
> 
> Who are you asking?
> 
> I just spend 10 minutes searching my computer. I’m not sure I can find this particular set.
> 
> > On Jun 8, 2016, at 3:56 PM, Nicholas Horton notifications@github.com wrote:
> > 
> > Can we leave out this example and use another example from later in the chapter (for which data are available?)
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub https://github.com/nicholasjhorton/IS4inR/issues/3#issuecomment-224708523, or mute the thread https://github.com/notifications/unsubscribe/AMdnA7ThEmHz2yArEsvEWU-eR4V6pwNVks5qJx5RgaJpZM4Iw_Xg.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
