### ISSUE TITLE
Section 5.1 Different Olympics, Different Data

### ISSUE THREAD

**Issue by wantpinow** [nicholasjhorton/IS4inR#4]
in SDM4, data from the 2012 Olympics is used in section 5.1, however in IS4, data from the 2008 Olympics is used. If anyone has access to the **2008 women's heptathlon** data that would be very helpful.

**Comment by nicholasjhorton** [comment]
Let's just see if you can get close with the stem and leaf plot of the data.

longjmp <- c(10, 20, 30), etc

**Comment by deveaux69** [comment]
> On Jun 8, 2016, at 3:54 PM, Nicholas Horton notifications@github.com wrote:
> 
> Let's just see if you can get close with the stem and leaf plot of the data.
> 
> longjmp <- c(10, 20, 30), etc
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub https://github.com/nicholasjhorton/IS4inR/issues/4#issuecomment-224708099, or mute the thread https://github.com/notifications/unsubscribe/AMdnA92ZyKHgrGrBKTlIoeCFngxb5zsjks5qJx3xgaJpZM4Iw_8f.

Time    Column 2
23.21   "Hyleas Fountain, United States"
23.39   "Kelly Sotherton, Great Britain"
23.39   "Karolina Tyminska, Poland"
23.64   "Jessica Zelinka, Canada"
23.95   "Tatyana Chernova, Russia"
23.97   "Jolanda Keizer, Netherlands"
24.24   "Anna Bogdanova, Russia"
24.28   "Kylie Wheeler, Australia"
24.34   "Susmita Singha Roy, India"
24.34   "Olga Kurban, Russia"
24.34   "Gretchen Quintana, Cuba"
24.35   "Ganna Melnichenko, Ukraine"
24.36   "Yuliya Tarasova, Uzbekistan"
24.39   "Nataliia Dobrynska, Ukraine"
24.47   "Liu Haili, China"
24.56   "Lucimara Silva, Brazil"
24.57   "Laurien Hoos, Netherlands"
24.62   "Shobha Jagadeeshppa Javur, India"
24.64   "Rebecca Wardell, New Zealand"
24.67   "Jennifer Oeser, Germany"
24.71   "Aiga Grabuste, Latvia"
24.74   "Jackie Johnson, United States"
24.9    "Antoinette Nana Djimou Ida, France"
24.92   "Pramila Ganapathy Gudanda, India"
24.99   "Linda Zublin, Switzerland"
25.02   "Ida Marcussen, Norway"
25.06   "Marie Collonville, France"
25.06   "Viktorija Zemaityte, Lithuania"
25.25   "Lilli Schwarzkopf, Germany"
25.36   "Kamila Chudzik, Poland"
25.4    "Austra Skujyte, Lithuania"
25.41   "Julie Hollman, Great Britain"
25.47   "Argyro Strataki, Greece"
25.49   "Kaie Kand, Estonia"
25.5    "Sonja Kesselschlager, Germany"
25.9    "Niina Kelo, Finland"
25.94   "Yana Maksimava, Belarus"
26.1    "Gyorgyi Farkas, Hungary"

**Comment by nicholasjhorton** [comment]
Thanks!

Nick

> On Jun 8, 2016, at 3:56 PM, deveaux69 notifications@github.com wrote:
> 
> > On Jun 8, 2016, at 3:54 PM, Nicholas Horton notifications@github.com wrote:
> > 
> > Let's just see if you can get close with the stem and leaf plot of the data.
> > 
> > longjmp <- c(10, 20, 30), etc
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub https://github.com/nicholasjhorton/IS4inR/issues/4#issuecomment-224708099, or mute the thread https://github.com/notifications/unsubscribe/AMdnA92ZyKHgrGrBKTlIoeCFngxb5zsjks5qJx3xgaJpZM4Iw_8f.
> 
> Time  Column 2
> 23.21 "Hyleas Fountain, United States"
> 23.39 "Kelly Sotherton, Great Britain"
> 23.39 "Karolina Tyminska, Poland"
> 23.64 "Jessica Zelinka, Canada"
> 23.95 "Tatyana Chernova, Russia"
> 23.97 "Jolanda Keizer, Netherlands"
> 24.24 "Anna Bogdanova, Russia"
> 24.28 "Kylie Wheeler, Australia"
> 24.34 "Susmita Singha Roy, India"
> 24.34 "Olga Kurban, Russia"
> 24.34 "Gretchen Quintana, Cuba"
> 24.35 "Ganna Melnichenko, Ukraine"
> 24.36 "Yuliya Tarasova, Uzbekistan"
> 24.39 "Nataliia Dobrynska, Ukraine"
> 24.47 "Liu Haili, China"
> 24.56 "Lucimara Silva, Brazil"
> 24.57 "Laurien Hoos, Netherlands"
> 24.62 "Shobha Jagadeeshppa Javur, India"
> 24.64 "Rebecca Wardell, New Zealand"
> 24.67 "Jennifer Oeser, Germany"
> 24.71 "Aiga Grabuste, Latvia"
> 24.74 "Jackie Johnson, United States"
> 24.9  "Antoinette Nana Djimou Ida, France"
> 24.92 "Pramila Ganapathy Gudanda, India"
> 24.99 "Linda Zublin, Switzerland"
> 25.02 "Ida Marcussen, Norway"
> 25.06 "Marie Collonville, France"
> 25.06 "Viktorija Zemaityte, Lithuania"
> 25.25 "Lilli Schwarzkopf, Germany"
> 25.36 "Kamila Chudzik, Poland"
> 25.4  "Austra Skujyte, Lithuania"
> 25.41 "Julie Hollman, Great Britain"
> 25.47 "Argyro Strataki, Greece"
> 25.49 "Kaie Kand, Estonia"
> 25.5  "Sonja Kesselschlager, Germany"
> 25.9  "Niina Kelo, Finland"
> 25.94 "Yana Maksimava, Belarus"
> 26.1  "Gyorgyi Farkas, Hungary"
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
