### ISSUE TITLE
Chapters 24 & 25

### ISSUE THREAD

**Issue by wantpinow** [nicholasjhorton/IS4inR#6]
Chapters 24 & 25 are online only chapters so I was unsure as to whether we were doing them or not. If we are, how do I access them to make drafts?

**Comment by nicholasjhorton** [comment]
Here they are: http://media.pearsoncmg.com/aw/aw_deveaux_introstats_4_2014/comp_website/stat4dv_comp_web_launch.html

> On Jun 23, 2016, at 7:59 PM, Patrick Frenett notifications@github.com wrote:
> 
> Chapters 24 & 25 are online only chapters so I was unsure as to whether we were doing them or not. If we are, how do I access them to make drafts?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
